apiVersion: apps/v1
kind: Deployment
metadata:
  name: hephaestus-gui
  namespace: hephaestus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hephaestus-gui
  template:
    metadata:
      labels:
        app: hephaestus-gui
    spec:
      containers:
        - name: hephaestus-gui
          image: NAME:TAG
          args: ["--prometheus.address=prometheus.monitoring:9090", "--saved.path=/../metrics/savedMetrics/metrics.json", "--config.path=/../metrics/configMetrics/metrics.json"] 
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: storage
              mountPath: metrics/savedMetrics
            - name: config-volume
              mountPath: metrics/configMetrics
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: hepheastus-gui-pvc
        - name: config-volume
          configMap:
            name: gui-configmap
            items:
            - key: metrics.json
              path: metrics.json 
