apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-adapter
  namespace: hephaestus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-adapter
  template:
    metadata:
      labels:
        app: metrics-adapter
    spec:
      containers:
        - name: metrics-adapter
          image: demo # <-- custom
          args: ["--backend=http://hephaestus-gui:8080"]
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
