apiVersion: v1
kind: Service
metadata:
  name: hephaestus-gui-frontend
  namespace: monitoring
spec:
  selector:
    app: hephaestus-gui
  type: LoadBalancer
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
