apiVersion: apps/v1
kind: Deployment
metadata:
  name: hephaestus-gui
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hephaestus-gui
  template:
    metadata:
      labels:
        app: hephaestus-gui
    spec:
      containers:
        - name: hephaestus-gui
          image: <IMAGE_NAME>:<TAG>
          args: ["--prometheus.address=prometheus:9090"] 
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: storage
              mountPath: /savedMetrics
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: hepheastus-gui-pvc