apiVersion: v1
kind: Service
metadata:
  name: metrics-adapter
  namespace: monitoring
spec:
  selector:
    app: hephaestus-gui
  type: LoadBalancer
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080