apiVersion: v1
kind: Service
metadata:
  name: palamedes
  namespace: palamedes
  labels:
    app: palamedes
spec:
  selector:
    app: palamedes
  ports:
    - name: http
      port: 8081
      targetPort: 8081
  type: ClusterIP
