${SPARQL_PREFIXES}
INSERT {
  ${IRI::subjectIri} cnee:${predicate} ${IRI::objectIri} .
  ${IRI::objectIri} cnee:${inversePredicate} ${IRI::subjectIri} .
}
WHERE {
  FILTER NOT EXISTS { ${IRI::subjectIri} cnee:${predicate} ${IRI::objectIri} }
}
