apiVersion: v1
kind: Service
metadata:
  name: kie-workbench
  namespace: kie
spec:
  selector:
    app: kie-workbench
  type: LoadBalancer
  ports:
    - protocol: "TCP"
      name: port-6080 #TODO
      port: 6080
      targetPort: 8080
    - protocol: "TCP"
      name: port-6001 #TODO
      port: 6001
      targetPort: 8001
    - protocol: "TCP"
      name: port-9990 #TODO
      port: 6990
      targetPort: 9990