apiVersion: v1
kind: Service
metadata:
  name: kie-server
  namespace: kie
spec:
  selector:
    app: kie-server
  type: LoadBalancer
  ports:
    - protocol: "TCP"
      name: port-7080 #TODO
      port: 7080
      targetPort: 8080
    - protocol: "TCP"
      name: port-7990 #TODO
      port: 7990
      targetPort: 9990