PREFIX moam: <http://www.semanticweb.org/patryk/ontologies/2026/4/MoaMont#>
DELETE DATA {
  moam:RestartPodAction moam:hasExecutionInstruction "kubectl rollout restart deployment/${resourceName} -n ${namespace} FAIL_NOW" .
};
INSERT DATA {
  moam:RestartPodAction moam:hasExecutionInstruction "kubectl rollout restart deployment/${resourceName} -n ${namespace}" .
}
