${SPARQL_PREFIXES}
DELETE { 
  ${IRI::targetResource} ${PREFIX::CNEE_PREFIX}:hasState ?oldState .
  ?oldState ?p ?o .
}
WHERE {
  ${IRI::targetResource} ${PREFIX::CNEE_PREFIX}:hasState ?oldState .
  ?oldState a ${IRI::anomalyType} .
  OPTIONAL { ?oldState ?p ?o . }
}
