${SPARQL_PREFIXES}
DELETE { 
  ${IRI::targetResource} ${PREFIX::CNEE_PREFIX}:hasState ?oldState .
  ?oldState ?p ?o .
}
INSERT {
  ${IRI::targetResource} ${PREFIX::CNEE_PREFIX}:hasState ${IRI::anomaly} .
  ${IRI::anomaly} a ${IRI::anomalyType} .
  ${IRI::anomaly} ${PREFIX::CNEE_PREFIX}:detectedAt ${LITERAL::timestamp} .
}
WHERE {
  OPTIONAL { 
    ${IRI::targetResource} ${PREFIX::CNEE_PREFIX}:hasState ?oldState .
    OPTIONAL { ?oldState ?p ?o . }
  }
}
