themis:
  graphdb:
    url: http://localhost:7200
    repository-id: moamont
  executors:
    kubernetes:
      management-url: http://localhost:8080
      timeout-ms: 5000
    logging:
      level: INFO
