apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-master
  namespace: online-boutique
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust-master
  template:
    metadata:
      labels:
        app: locust-master
    spec:
      nodeSelector:
        node-role: load-gen
      containers:
      - name: master
        image: locustio/locust
        args: ["--master"]
        ports:
        - containerPort: 8089
        - containerPort: 5557
        volumeMounts:
        - name: locust-script
          mountPath: /home/locust
      - name: exporter
        image: locustio/locust
        command: ["python3", "/home/locust/locust-exporter.py"]
        env:
        - name: LOCUST_METRIC_NAMESPACE
          value: online-boutique
        - name: LOCUST_METRIC_NAME
          value: frontend
        ports:
        - name: metrics
          containerPort: 9646
        volumeMounts:
        - name: locust-script
          mountPath: /home/locust
      volumes:
      - name: locust-script
        configMap:
          name: locust-script-boutique
---
apiVersion: v1
kind: Service
metadata:
  name: locust-master
  namespace: online-boutique
  labels:
    app: locust-master
spec:
  selector:
    app: locust-master
  ports:
  - name: web
    port: 8089
    targetPort: 8089
  - name: communication
    port: 5557
    targetPort: 5557
  - name: metrics
    port: 9646
    targetPort: 9646
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-worker
  namespace: online-boutique
spec:
  replicas: 4
  selector:
    matchLabels:
      app: locust-worker
  template:
    metadata:
      labels:
        app: locust-worker
    spec:
      nodeSelector:
        node-role: load-gen
      containers:
      - name: worker
        image: locustio/locust
        args: ["--worker", "--master-host=locust-master"]
        env:
        - name: LOCUST_TARGET_HOST
          value: "http://frontend.online-boutique.svc.cluster.local"
        volumeMounts:
        - name: locust-script
          mountPath: /home/locust
      volumes:
      - name: locust-script
        configMap:
          name: locust-script-boutique
